In [16]:
# %% [markdown]
# ### 2022년 5월 sales의 중앙값을 구하시오
# 
# - 데이터셋 : basic2.csv 
# - 오른쪽 상단 copy&edit 클릭 -> 예상문제 풀이 시작

# 라이브러리 불러오기
import pandas as pd

# 데이터 불러오기
df = pd.read_csv("../input/bigdatacertificationkr/basic2.csv")
df.head()
df.info()
df['Date'] = pd.to_datetime(df['Date'])
df.info()

df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day

cond1 = df['year'] == 2022
cond2 = df['month'] == 5
df2 = df[cond1 & cond2]

answer = df2['Sales'].median()
print(answer)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    730 non-null    object
 1   Sales   730 non-null    int64
 2   PV      730 non-null    int64
 3   UV      684 non-null    float64
 4   Events  730 non-null    int64
dtypes: float64(1), int64(3), object(1)
memory usage: 28.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    730 non-null    datetime64[ns]
 1   Sales   730 non-null    int64
 2   PV      730 non-null    int64
 3   UV      684 non-null    float64
 4   Events  730 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 28.6 KB
1477685.0