## basic1 데이터에서 f4가 E로 시작하면서 부산에 살고 20대인 사람은 몇 명일까요?

In [5]:
import pandas as pd
df = pd.read_csv("../input/bigdatacertificationkr/basic1.csv")
df

cond1 = df['f4'].str[:1] == "E"
cond2 = df['city'] =='부산'
cond3 = ((df['age'] >= 20) & (df['age'] <= 29))

df2 = df[cond1 & cond2 & cond3]
print(len(df2))

0

In [ ]:
import pandas as pd
df = pd.read_csv("../input/bigdatacertificationkr/basic1.csv")
df['EI'] = df['f4'].str[:1]
cond1 = df['EI'] == "E"
cond2 = df['city'] == "부산"
cond3 = (df['age'] >= 20) & (df['age'] < 30)

print(len(df[cond1 & cond2 & cond3]))